### ISSUE TITLE
Solution

### ISSUE THREAD

**Issue by juye-ops** [juye-ops/docker-practice#1]
### Frontend
```dockerfile
FROM node:18

WORKDIR /root

COPY ./package.json /root/

RUN npm install

ENV NODE_PATH=/root/node_modules

WORKDIR /root/frontend

CMD ["npm", "start"]
```

### Backend
```dockerfile
FROM python:3

RUN pip install fastapi uvicorn pymongo

COPY ./app.py /root

WORKDIR /root/

CMD ["python", "app.py"]
```

### 1. network 생성
- 같은 네트워크로 생성하여 frontend:3000, backend:5000, database:27017 등의 간편한 도메인 접근 허용
```bash
sudo docker network create --subnet 172.24.0.0/16 docknet
```

### 2. Frontend 컨테이너 생성
```bash
# 위에서 작성한 dockerfile 기반 image 생성
sudo docker build -t front frontend/
# 생성한 image 기반으로 컨테이너 생성
sudo docker run --name frontend --network docknet -p 3000:3000 -v .:/root/frontend front
```
### 3. Backend 컨테이너 생성
```bash
# 위에서 작성한 dockerfile 기반 image 생성
sudo docker build -t back backend/
# 생성한 image 기반으로 컨테이너 생성
sudo docker run --name backend -p 5000:5000 --network docknet back
```

### 4. Backend 컨테이너 생성
- mongoDB는 기존 docker hub에 존재하는 image를 기반하므로 별도의 build 과정 생략
```bash
# docker hub에서 탐색한 image를 바로 호출하여 컨테이너 생성
sudo docker run --name database -p 27017:27017 --network docknet mongo
```

### IaC
```yaml
version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    networks:
      docknet:
        ipv4_address: 172.24.0.2
    volumes:
      - ./frontend/:/root/frontend
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/:/root/backend
    depends_on:
      - database
    networks:
      docknet:
        ipv4_address: 172.24.0.3

  database:
    image: mongo:6.0
    container_name: database
    restart: always
    ports:
      - 27017:27017
    networks:
      docknet:
        ipv4_address: 172.24.0.4

networks:
  docknet:
    external: false
    ipam:
      config:
        - subnet: 172.24.0.0/16
```

### Command line
```bash
sudo docker compose up
```
